"""Initial Schema

Revision ID: 4964188b6a82
Revises: 
Create Date: 2023-12-03 22:04:02.175839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4964188b6a82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('model_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_response_timestamp'), ['timestamp'], unique=False)

    op.create_table('user_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('user_classification', sa.Integer(), nullable=True),
    sa.Column('user_ip', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_query', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_query_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_query_tweet_id'), ['tweet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_query_tweet_id'))
        batch_op.drop_index(batch_op.f('ix_user_query_timestamp'))

    op.drop_table('user_query')
    with op.batch_alter_table('model_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_response_timestamp'))

    op.drop_table('model_response')
    op.drop_table('tweet')
    # ### end Alembic commands ###
