"""Initial Schema

Revision ID: 904917072f77
Revises: 
Create Date: 2023-12-05 16:17:21.603487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904917072f77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_text', sa.String(length=256), nullable=False),
    sa.Column('user_ip', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_request_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_request_timestamp'))

    op.drop_table('user_request')
    # ### end Alembic commands ###
