"""User Classification

Revision ID: fa63e5e4aaf0
Revises: 904917072f77
Create Date: 2023-12-05 18:03:01.243215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa63e5e4aaf0'
down_revision = '904917072f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_classification', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.drop_column('user_classification')

    # ### end Alembic commands ###
