version: '3'

services:
  app:
    build: ../..
    image: ghcr.io/florianehmann/twitter-emotion-webapp:latest
    environment:
      - SECRET_KEY=<some-secret-key>
      - INFERENCE_API_TOKEN=<api-token>
    ports:
      - "8000:5000"
    volumes:
      - ./logs:/home/twitter-emotion/logs
